config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  resources :course_criterions
  resources :faculties do
    collection { post :import}
  end
  resources :courses do
    collection { post :import}
  end
  resources :courses
  resources :administrators
  resources :faculty_courses
  resources :criterions
  get 'faculties/index'
  get 'faculties/import'
  get 'courses/index'
  get 'courses/import'
  get '/reports', to: 'reports#index', as: 'reports'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/faculty_courses_controller.rb
class FacultyCoursesController < ApplicationController
  before_action :set_faculty_course, only: [:show, :edit, :update, :destroy]

  # GET /faculty_courses
  # GET /faculty_courses.json
  def index
    @faculty_courses = FacultyCourse.all
  end

  # GET /faculty_courses/1
  # GET /faculty_courses/1.json
  def show
  end

  # GET /faculty_courses/new
  def new
    @faculty_course = FacultyCourse.new
  end

  # GET /faculty_courses/1/edit
  def edit
  end

  # POST /faculty_courses
  # POST /faculty_courses.json
  def create
    @faculty_course = FacultyCourse.new(faculty_course_params)

    respond_to do |format|
      if @faculty_course.save
        format.html { redirect_to @faculty_course, notice: 'Faculty assignment was successfully created.' }
        format.json { render :show, status: :created, location: @faculty_course }
      else
        format.html { render :new }
        format.json { render json: @faculty_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculty_courses/1
  # PATCH/PUT /faculty_courses/1.json
  def update
    respond_to do |format|
      if @faculty_course.update(faculty_course_params)
        format.html { redirect_to @faculty_course, notice: 'Faculty assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty_course }
      else
        format.html { render :edit }
        format.json { render json: @faculty_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculty_courses/1
  # DELETE /faculty_courses/1.json
  def destroy
    @faculty_course.destroy
    respond_to do |format|
      format.html { redirect_to faculty_courses_url, notice: 'Faculty assignment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty_course
      @faculty_course = FacultyCourse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_course_params
      params.require(:faculty_course).permit(:course_id, :course, :faculty_id, :faculty, faculties_attributes:[:faculty_id, :fname, :lname, :_destroy])
    end

end

app/helpers/faculty_courses_helper.rb
module FacultyCoursesHelper
end

app/views/faculty_courses/_form.html.erb
<%#= form_with(model: faculty_course, local: true) do |f| %>
<%= form_for @faculty_course do |f| %>
  <% if faculty_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faculty_course.errors.count, "error") %> prohibited this faculty_course from being saved:</h2>

      <ul>
      <% faculty_course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_id %>
    <%= f.collection_select :course_id, Course.all, :id, :name %>
  </div>

  <div class="field">
      <%= f.nested_fields_for :faculties, legend: "Faculty " do |ff| %>
        <%= ff.label :faculty_id, "Name" %>
        <%= f.collection_select :faculty_id, Faculty.all, :id, :fullname %>

        <button type="button" class="btn btn-danger"><%= ff.remove_nested_fields_link "X" %></button>
  <% end %>
  </div>

  <div class="actions">
    <button type="button" class="btn btn-default"><%= f.add_nested_fields_link :faculties, 'Assign another Faculty Member' %></button>

    <%= f.submit "Submit", :class => 'btn btn-default' %>

  </div>
<% end %>

app/views/faculty_courses/edit.html.erb
<h1>Editing Faculty Assignment</h1>

<%= render 'form', faculty_course: @faculty_course %>

<%= link_to 'Show', @faculty_course %> |
<%= link_to 'Back', faculty_courses_path %>

app/views/faculty_courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faculty Assignments</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Faculty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faculty_courses.each do |faculty_course| %>
      <tr>
        <td><%= faculty_course.course.name %></td>
        <td><%= faculty_course.faculty.fullname %>, </td>
        <td><%= link_to 'Show', faculty_course %></td>
        <td><%= link_to 'Edit', edit_faculty_course_path(faculty_course) %></td>
        <td><%= link_to 'Destroy', faculty_course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-default"><%= link_to 'New Faculty Course', new_faculty_course_path %></button>

app/views/faculty_courses/new.html.erb
<h1>New Faculty Assignment</h1>

<%= render 'form', faculty_course: @faculty_course %>

<%= link_to 'Back', faculty_courses_path %>

app/views/faculty_courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @faculty_course.course.name %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @faculty_course.faculty.fullname %>
</p>

<%= link_to 'Edit', edit_faculty_course_path(@faculty_course) %> |
<%= link_to 'Back', faculty_courses_path %>