config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  resources :course_criterions
  resources :faculties do
    collection { post :import}
  end
  resources :courses do
    collection { post :import}
  end
  resources :courses
  resources :administrators
  resources :faculty_courses
  resources :criterions
  get 'faculties/index'
  get 'faculties/import'
  get 'courses/index'
  get 'courses/import'
  get '/reports', to: 'reports#index', as: 'reports'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  require 'csv'
  validates :email, presence: true, uniqueness: true

  has_many :courses, through: :faculty_courses
  has_many :faculty_courses

  accepts_nested_attributes_for :faculty_courses
  accepts_nested_attributes_for :courses

  # def self.import(file)
  #   imported_count = 0
  #   CSV.foreach(file.path, encoding: 'UTF-8', headers: true, header_converters: :symbol, converters: :all) do |row|
  #     if Faculty.exists?(email: row[:email])
  #       Rails.logger.warn("Faculty member with email #{row[:email]} already exists")
  #     else
  #       Faculty.create! row.to_hash
  #       imported_count += 1
  #     end
  #   end
  #   imported_count
  # end

  def self.import(file)
    CSV.foreach(file.path, { encoding: "UTF-8", headers: true, header_converters: :symbol, converters: :all}) do |row|
      Faculty.create! row.to_hash
    end
  end

  def fullname
    "#{fname} #{lname}"
  end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET /faculties
  # GET /faculties.json
  def index
    @faculties = Faculty.all
  end

  # def import
  #   imported_count = 0
  #   CSV.foreach(params[:file].path, encoding: 'UTF-8', headers: true, header_converters: :symbol, converters: :all) do |row|
  #     if Faculty.exists?(email: row[:email])
  #       Rails.logger.warn("Faculty member with email #{row[:email]} already exists")
  #     else
  #       Faculty.create! row.to_hash
  #       imported_count += 1
  #     end
  #   end
  #   imported_count
  # end

  def import
    if params[:file]
      Faculty.import(params[:file])
      redirect(faculties_path, "Faculty data imported!")
    else
      redirect(faculties_path, "Please upload a CSV file")
    end
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def redirect(url, text)
    redirect_to url, notice: text
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_params
      params.require(:faculty).permit(:fname, :lname, :title, :office, :email, :phone)
    end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/faculties/_form.html.erb
<%= form_with(model: faculty, local: true) do |form| %>
  <% if faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
      <% faculty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fname, "First Name" %>
    <%= form.text_field :fname %>
  </div>

  <div class="field">
    <%= form.label :lname, "Last Name"%>
    <%= form.text_field :lname %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :office %>
    <%= form.text_field :office %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h1>Editing Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Show', @faculty %> |
<%= link_to 'Back', faculties_path %>

app/views/faculties/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6">
    <h1>Faculty</h1>
    <table>
      <thead>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Title</th>
          <th>Office</th>
          <th>Email</th>
          <th>Phone</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @faculties.each do |faculty| %>
          <tr>
            <td><%= faculty.fname %></td>
            <td><%= faculty.lname %></td>
            <td><%= faculty.title %></td>
            <td><%= faculty.office %></td>
            <td><%= faculty.email %></td>
            <td><%= faculty.phone %></td>
            <td><%= link_to 'Show', faculty %></td>
            <td><%= link_to 'Edit', edit_faculty_path(faculty) %></td>
            <td><%= link_to 'Destroy', faculty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <button type="button" class="btn btn-default"><%= link_to 'New Faculty', new_faculty_path %></button>
  </div>

  <div class="col-md-6">
    <h1>Import Data (.csv)</h1>
    <p>Use these controls to import data into the faculty table in .csv format.
      An example of the correct format for this file can be downloaded <a href="faculty_example.csv" download>here</a>.</p>
    <p>
      <%= form_tag import_faculties_path, multipart: true do %>
        <button class="btn btn-default btn-file">Choose File<%= file_field_tag :file %></button>
        <%= submit_tag "Import CSV", :class => 'btn btn-default' %>
      <% end %>
    </p>
  </div>
</div>

app/views/faculties/new.html.erb
<h1>New Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Back', faculties_path %>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @faculty.fname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @faculty.lname %>
</p>

<p>
  <strong>Title:</strong>
  <%= @faculty.title %>
</p>

<p>
  <strong>Office:</strong>
  <%= @faculty.office %>
</p>

<p>
  <strong>Email:</strong>
  <%= @faculty.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @faculty.phone %>
</p>

<%= link_to 'Edit', edit_faculty_path(@faculty) %> |
<%= link_to 'Back', faculties_path %>