config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  resources :course_criterions
  resources :faculties do
    collection { post :import}
  end
  resources :courses do
    collection { post :import}
  end
  resources :courses
  resources :administrators
  resources :faculty_courses
  resources :criterions
  get 'faculties/index'
  get 'faculties/import'
  get 'courses/index'
  get 'courses/import'
  get '/reports', to: 'reports#index', as: 'reports'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/criterion.rb
class Criterion < ApplicationRecord
  has_many :courses, through: :course_criterion


  def name_plus_desc
    "#{name} - #{description}"
  end

end

app/controllers/criterions_controller.rb
class CriterionsController < ApplicationController
  before_action :set_criterion, only: [:show, :edit, :update, :destroy]

  # GET /criterions
  # GET /criterions.json
  def index
    @criterions = Criterion.all
  end

  # GET /criterions/1
  # GET /criterions/1.json
  def show
  end

  # GET /criterions/new
  def new
    @criterion = Criterion.new
  end

  # GET /criterions/1/edit
  def edit
  end

  # POST /criterions
  # POST /criterions.json
  def create
    @criterion = Criterion.new(criterion_params)

    respond_to do |format|
      if @criterion.save
        format.html { redirect_to @criterion, notice: 'Criteria was successfully created.' }
        format.json { render :show, status: :created, location: @criterion }
      else
        format.html { render :new }
        format.json { render json: @criterion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /criterions/1
  # PATCH/PUT /criterions/1.json
  def update
    respond_to do |format|
      if @criterion.update(criterion_params)
        format.html { redirect_to @criterion, notice: 'Criteria was successfully updated.' }
        format.json { render :show, status: :ok, location: @criterion }
      else
        format.html { render :edit }
        format.json { render json: @criterion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /criterions/1
  # DELETE /criterions/1.json
  def destroy
    @criterion.destroy
    respond_to do |format|
      format.html { redirect_to criterions_url, notice: 'Criteria was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_criterion
      @criterion = Criterion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def criterion_params
      params.require(:criterion).permit(:name, :description, :string)
    end
end

app/helpers/criterions_helper.rb
module CriterionsHelper
end

app/views/criterions/_form.html.erb
<%= form_with(model: criterion, local: true) do |form| %>
  <% if criterion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(criterion.errors.count, "error") %> prohibited this criterion from being saved:</h2>

      <ul>
      <% criterion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/criterions/edit.html.erb
<h1>Editing ABET Criterion</h1>

<%= render 'form', criterion: @criterion %>

<%= link_to 'Show', @criterion %> |
<%= link_to 'Back', criterions_path %>

app/views/criterions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ABET Criterion</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @criterions.each do |criterion| %>
      <tr>
        <td><%= criterion.name %></td>
        <td><%= criterion.description %></td>
        <td><%= link_to 'Show', criterion %></td>
        <td><%= link_to 'Edit', edit_criterion_path(criterion) %></td>
        <td><%= link_to 'Destroy', criterion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-default"><%= link_to 'New Criterion', new_criterion_path %></button>

app/views/criterions/new.html.erb
<h1>New ABET Criterion</h1>

<%= render 'form', criterion: @criterion %>

<%= link_to 'Back', criterions_path %>

app/views/criterions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @criterion.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @criterion.description %>
</p>

<%= link_to 'Edit', edit_criterion_path(@criterion) %> |
<%= link_to 'Back', criterions_path %>